/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainGUI.java
 *
 * Created on Feb 17, 2009, 9:58:58 AM
 */

package version7;

import java.awt.Color;
import javax.swing.JComboBox;

/**
 *
 * @author jlombardo
 */
public class MainGUI extends javax.swing.JFrame {
    private Duck[] ducks;
    private QuackBehavior[] quacks;
    private FlyBehavior[] flys;
    private Duck duck;
    private QuackBehavior quack;
    private FlyBehavior fly;

    /** Creates new form MainGUI */
    public MainGUI() {
        initDucks();
        initQuacks();
        initFlys();
        initComponents();
        initResultsMsg();
        this.getContentPane().setBackground(new java.awt.Color(204, 255, 204));
    }

    private void initResultsMsg() {
        duck = (Duck)cboDucks.getItemAt(0);
        quack = (QuackBehavior)cboQuacks.getItemAt(0);
        fly = (FlyBehavior)cboFlys.getItemAt(0);
        resultMsg.setText(duck.toString() +
                ", " + quack.toString() + ", " + fly.toString());
    }

    private void initDucks() {
        ducks = new Duck[3];
        ducks[0] = new MallardDuck();
        ducks[1] = new ModelDuck();
        ducks[2] = new RubberDuck();
    }

    private void initQuacks() {
        quacks = new QuackBehavior[3];
        quacks[0] = new Quack();
        quacks[1] = new MuteQuack();
        quacks[2] = new Squeak();
    }

    private void initFlys() {
        flys = new FlyBehavior[3];
        flys[0] = new FlyNoWay();
        flys[1] = new FlyRocketPowered();
        flys[2] = new FlyWithWings();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cboDucks = new JComboBox(ducks);
        jLabel3 = new javax.swing.JLabel();
        cboQuacks = new JComboBox(quacks);
        jLabel4 = new javax.swing.JLabel();
        cboFlys = new JComboBox(flys);
        jPanel1 = new javax.swing.JPanel();
        resultMsg = new javax.swing.JLabel();
        btnActivateDuck = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mini Duck Similuator");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mini Duck Simuilator");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setText("Choose Duck");

        cboDucks.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                duckSelectionHandler(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel3.setText("Choose Quack Behavior");

        cboQuacks.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                quackSelectionHandler(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel4.setText("Choose Fly Behavior");

        cboFlys.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                flySelectionHandler(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Current Settings"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resultMsg, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resultMsg)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        btnActivateDuck.setText("Activate Runtime Changes in Console");
        btnActivateDuck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivateDuckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                                .addComponent(cboQuacks, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                                .addComponent(cboDucks, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                                .addComponent(cboFlys, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(btnActivateDuck)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cboDucks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cboQuacks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboFlys, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(32, 32, 32)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnActivateDuck)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void duckSelectionHandler(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_duckSelectionHandler
        duck = (Duck)evt.getItem();
        resultMsg.setText(duck.toString()
                + ", " + quack.toString() + ", " + fly.toString());
}//GEN-LAST:event_duckSelectionHandler

    private void quackSelectionHandler(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_quackSelectionHandler
        quack = (QuackBehavior)evt.getItem();
        resultMsg.setText(duck.toString() + ", "
                + quack.toString() + ", " + fly.toString());
    }//GEN-LAST:event_quackSelectionHandler

    private void flySelectionHandler(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_flySelectionHandler
        fly = (FlyBehavior)evt.getItem();
        resultMsg.setText(duck.toString() + ", "
                + quack.toString() + ", " + fly.toString());
    }//GEN-LAST:event_flySelectionHandler

    private void btnActivateDuckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivateDuckActionPerformed
        System.out.println("\n");
        duck.display();
        if(quack != null) duck.setQuackBehavior(quack);
        duck.performQuack();
        if (fly != null) duck.setFlyBehavior(fly);
        duck.performFly();
    }//GEN-LAST:event_btnActivateDuckActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActivateDuck;
    private javax.swing.JComboBox cboDucks;
    private javax.swing.JComboBox cboFlys;
    private javax.swing.JComboBox cboQuacks;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel resultMsg;
    // End of variables declaration//GEN-END:variables

}
